package io.seata.sample.dao;

import io.seata.sample.entity.Seataorder;
import io.seata.sample.entity.SeataorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeataorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    long countByExample(SeataorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int deleteByExample(SeataorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int insert(Seataorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int insertSelective(Seataorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    List<Seataorder> selectByExample(SeataorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    Seataorder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Seataorder record, @Param("example") SeataorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int updateByExample(@Param("record") Seataorder record, @Param("example") SeataorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int updateByPrimaryKeySelective(Seataorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seataorder
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    int updateByPrimaryKey(Seataorder record);
}