eureka:
    instance:
        hostname: 106.54.194.33
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
    hystrix:
        enabled: false
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 10000
logging:
    level:
        io:
            seata: info
server:
    port: 8180
spring:
    application:
        name: order-server
    cloud:
        alibaba:
            seata:
                tx-service-group: fsp_tx_group
    jpa: 
        database: mysql
        show-sql: true
        hibernate: 
            ddl-auto: update
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.54.194.33/mystdb?serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: admin
