package io.seata.sample.entity;

import java.math.BigDecimal;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.count
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private BigDecimal money;

    public BigDecimal getMoney() {
		return money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.product_id
     *
     * @return the value of order.product_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.product_id
     *
     * @param productId the value for order.product_id
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.count
     *
     * @return the value of order.count
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.count
     *
     * @param count the value for order.count
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
//    public Long getMoney() {
//        return money;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
//    public void setMoney(Long money) {
//        this.money = money;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Tue Apr 07 21:34:52 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}