package io.seata.sample.entity;

import java.math.BigDecimal;

public class Seataorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seataorder.id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seataorder.user_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seataorder.product_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seataorder.count
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seataorder.money
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    private BigDecimal money;

	public BigDecimal getMoney() {
		return money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seataorder.id
     *
     * @return the value of seataorder.id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seataorder.id
     *
     * @param id the value for seataorder.id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seataorder.user_id
     *
     * @return the value of seataorder.user_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seataorder.user_id
     *
     * @param userId the value for seataorder.user_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seataorder.product_id
     *
     * @return the value of seataorder.product_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seataorder.product_id
     *
     * @param productId the value for seataorder.product_id
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seataorder.count
     *
     * @return the value of seataorder.count
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seataorder.count
     *
     * @param count the value for seataorder.count
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seataorder.money
     *
     * @return the value of seataorder.money
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
//    public Long getMoney() {
//        return money;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seataorder.money
     *
     * @param money the value for seataorder.money
     *
     * @mbg.generated Tue Apr 07 22:52:10 CST 2020
     */
//    public void setMoney(Long money) {
//        this.money = money;
//    }
}